---

- name: "Load the amd packages dictionary for the target distribution"
  include_vars: "amd-packages-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"

# 1) Check if components are installed of other version than specified by variable.
#   - if other version installed, then remove and clean up

# 2) Install AMD toolchain
- include_tasks: ./tools/main.yml

# 3) Install XRT
#- include_tasks: ./xrt.yml


# 4) Install deployement targets
#
# 5) Install development targets
#
# 6) Install Vitis AI (optional)
