---

- name: Set XRT facts
  ansible.builtin.set_fact:
    amd_apm_xrt_download_url: "{{ amd_apm_packages[ansible_distribution][ansible_distribution_version][amd_apm_release]['xrt']['url'] }}"
    amd_apm_xrt_package: "{{ amd_apm_packages[ansible_distribution][ansible_distribution_version][amd_apm_release]['xrt']['package'] }}"
    amd_apm_xrt_checksum: "{{ amd_apm_packages[ansible_distribution][ansible_distribution_version][amd_apm_release]['xrt']['checksum'] }}"

- name: Ensure XRT download directory exists
  ansible.builtin.file:
    path: "{{ amd_apm_download_path }}/xrt"
    state: directory

- name: Download XRT package
  ansible.builtin.get_url:
    url: "{{ amd_apm_xrt_download_url }}{{ amd_apm_xrt_package }}"
    dest: "{{ amd_apm_download_path }}/xrt"
    checksum: "{{ amd_apm_xrt_checksum }}"

- name: Install XRT package
  ansible.builtin.package:
    deb: "{{ amd_apm_download_path }}/xrt/{{ amd_apm_xrt_package }}"
    state: present

- name: Add XRT setup script to global .bashrc
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: "source {{ amd_apm_install_path }}/xrt/setup.sh"
