---

- name: "[XRT {{ amd_apm_release.release }}] Set XRT package facts"
  ansible.builtin.set_fact:
    amd_apm_xrt_package: "{{ amd_apm_packages[amd_apm_release.release]['runtime']['xrt']['package'] }}"
    amd_apm_xrt_checksum: "{{ amd_apm_packages[amd_apm_release.release]['runtime']['xrt']['checksum_sha256'] }}"

- name: "[XRT {{ amd_apm_release.release }}] Set XRT release path facts"
  ansible.builtin.set_fact:
    amd_apm_xrt_release_install_path: "{{ amd_apm_xrt_install_path }}/{{ amd_apm_release.release }}"
    amd_apm_xrt_package_path: "{{ amd_apm_download_path }}/{{ amd_apm_release.release }}/{{ amd_apm_xrt_package }}"


# DOWNLOAD

- name: "[XRT {{ amd_apm_release.release }}] Ensure XRT package exists"
  ansible.builtin.file:
    path: "{{ amd_apm_xrt_package_path }}"
    state: file

#- name: "[XRT {{ amd_apm_release.release }}] Download XRT package"
#  ansible.builtin.get_url:
#    url: "{{ amd_apm_xrt_download_url }}{{ amd_apm_xrt_package }}"
#    dest: "{{ amd_apm_xrt_download_path }}"


# INSTALL
- name: "[XRT {{ amd_apm_release.release }}] Install prerequisite Boost libraries"
  package:
    name:
      - libboost-filesystem1.74.0
      - libboost-program-options1.74.0
    state: present

- name: "[XRT {{ amd_apm_release.release }}] Ensure XRT release install directory exists"
  ansible.builtin.file:
    path: "{{ amd_apm_xrt_release_install_path }}"
    state: directory

- name: "[XRT {{ amd_apm_release.release }}] Install XRT package"
  ansible.builtin.command: "dpkg-deb -x {{ amd_apm_xrt_package_path }} {{ amd_apm_xrt_release_install_path }}"


# POST INSTALL

- name: "[XRT {{ amd_apm_release.release }}] Add XRT setup script to global .bashrc"
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: "source {{ amd_apm_xrt_release_install_path }}/opt/xilinx/xrt/setup.sh"
  when:
    - not more_than_one_release
    - amd_apm_runtime_set_bash_environment_variables
