---

# DETERMINE WHAT NEEDS TO BE DONE

- name: Determine what needs to be done
  include_tasks: determine_state.yml


# REMOVE

- name: Uninstall Vitis/Vivado releases
  include_tasks: ./uninstall.yml
  loop: "{{ releases_to_uninstall }}"
  loop_control:
    loop_var: amd_apm_release


# CHECK SPACE

- name: Check disk space
  include_tasks: check_disk_space.yml
  when: not amd_apm_tools_skip_disk_space_check


# INSTALL

- name: Install AMD Toolchain
  include_tasks: "./install-{{ amd_apm_release.tools_install_method }}.yml"
  loop: "{{ amd_apm_releases_normalized | selectattr('release', 'in', releases_to_install ) }}"
  loop_control:
    loop_var: amd_apm_release

- name: Post installation tasks (set environment variables etc.)
  include_tasks: ./post-install.yml
  loop: "{{ amd_apm_releases_normalized | selectattr('release', 'in', releases_to_install ) }}"
  loop_control:
    loop_var: amd_apm_release
  vars:
    more_than_one_release: (releases_to_install + releases_already_correct) | length > 1
