---

# DETERMINE WHAT NEEDS TO BE DONE

- name: Determine what needs to be done
  include_tasks: determine_state.yml


# REMOVE

- name: Uninstall Vitis/Vivado releases with state absent
  include_tasks: ./uninstall.yml
  loop: "{{ releases_to_uninstall + releases_to_reinstall }}"
  loop_control:
    loop_var: amd_apm_release


# CHECK SPACE

- name: Check disk space
  include_tasks: check_disk_space.yml
  when: not amd_apm_tools_skip_disk_space_check


# INSTALL

- name: Set AMD Toolchain path facts
  ansible.builtin.set_fact:
    amd_apm_tools_download_path: "{{ amd_apm_download_path }}/tools"

- name: Install AMD Toolchain
  include_tasks: "./install-{{ amd_apm_release.install_method }}.yml"
  loop: "{{ amd_apm_releases_normalized | selectattr('release', 'in', releases_to_install + releases_to_reinstall) }}"
  loop_control:
    loop_var: amd_apm_release

- name: Post installation tasks (set environment variables etc.)
  include_tasks: ./post-install.yml
  loop: "{{ amd_apm_releases_normalized | selectattr('release', 'in', releases_to_install + releases_to_reinstall) }}"
  loop_control:
    loop_var: amd_apm_release

