---

## Note: from release 2025.1 onwards, the installation layout changed.
##  Up to 2024.2, the directory for a specific release was inside the directory for the program (eg. <install_path>/Vivado/2024.2)
##  From 2025.1 onwards, all program directories are in a release directory (eg. <install_path>/2025.1/Vivado)
##

- name: Uninstall tasks for releases up to 2024.2
  when: "{{ amd_apm_release.split('.')[0] | int }} <= 2024"
  block:
    - name: "[Uninstall {{ amd_apm_release }}] Remove program files"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ amd_apm_tools_install_path }}/Vivado/{{ amd_apm_release }}"
        - "{{ amd_apm_tools_install_path }}/Vitis_HLS/{{ amd_apm_release }}"
        - "{{ amd_apm_tools_install_path }}/Vitis/{{ amd_apm_release }}"
        - "{{ amd_apm_tools_install_path }}/Model_Composer/{{ amd_apm_release }}"

    - name: "[Uninstall {{ amd_apm_release }}] Remove bash source scripts"
      lineinfile:
        path: /etc/bash.bashrc
        regexp: '^source\s+{{ amd_apm_tools_install_path }}/[^/]+/{{ amd_apm_release }}/settings64\.sh'
        state: absent

    - name: "[Uninstall {{ amd_apm_release }}] Remove Model Composer from PATH"
      lineinfile:
        path: /etc/bash.bashrc
        regexp: '^export\s+PATH={{ amd_apm_tools_install_path }}/Model_Composer/{{ amd_apm_release }}/bin:\$PATH'
        state: absent

- name: Uninstall tasks for releases from 2025.1 and onwards
  when: "{{ amd_apm_release.split('.')[0] | int }} >= 2025"
  block:
    - name: "[Uninstall {{ amd_apm_release }}] Remove program files"
      file:
        path: "{{ amd_apm_tools_install_path }}/{{ amd_apm_release }}"
        state: absent

    - name: "[Uninstall {{ amd_apm_release }}] Remove bash source scripts"
      lineinfile:
        path: /etc/bash.bashrc
        regexp: '^source\s+{{ amd_apm_tools_install_path }}/{{ amd_apm_release }}/[^/]+/settings64\.sh'
        state: absent

    - name: "[Uninstall {{ amd_apm_release }}] Remove Model Composer from PATH"
      lineinfile:
        path: /etc/bash.bashrc
        regexp: '^export\s+PATH={{ amd_apm_tools_install_path }}/{{ amd_apm_release }}/Model_Composer/bin:\$PATH'
        state: absent

